# Driver de PostgreSQL
driver: org.postgresql.Driver

# URL de conexión
url: jdbc:postgresql://localhost:5432/liquibase_demo

# Usuario de la base de datos
username: postgres

# Contraseña
password: admin123

# Archivo changelog
changeLogFile: changelog.sql